Repository Like-House/FE, pull requests merged in 2024-08, with the labels that each got.

#82 [Feat]feature/#81 photomainpage, alertpage 구현
  src/assets/images/avatar.png
  src/assets/images/calendar.png
  src/assets/images/messenger.png
  src/components/common/avatar/Avatar.jsx
  src/components/common/avatar/Avatar.style.js
  src/mockdata/db.json
  src/pages/alert/AlertMainPage.jsx
  src/pages/alert/AlertMainPage.style.js
  src/pages/alert/components/alertbox/AlertBox.jsx
  src/pages/alert/components/alertbox/AlertBox.style.js
  src/pages/photo/PhotoMainPage.jsx
  src/pages/photo/PhotoMainPage.style.js
  src/store/useCalendarStore.js
  src/theme/theme.js
Labels: ✨ Feat

#56 [Feat]feature/#55 개인정보 수정 페이지 구현 (미완)
  package.json
  src/App.jsx
  src/components/common/avatar/Avatar.jsx
  src/components/common/avatar/Avatar.style.js
  src/components/common/input/CustomInput.style.js
  src/constants/path.js
  src/hooks/useImageUpload.js
  src/pages/index.js
  src/pages/setting/EditProfile/EditProfile.jsx
  src/pages/setting/EditProfile/EditProfile.style.js
Labels: ✨ Feat

#85 [Style] feature/#84 sidebar 디자인 수정
  src/assets/images/moreBox.svg
  src/components/common/sidebar/SideBar.jsx
  src/components/common/sidebar/SideBar.style.js
  src/layout/home/HomeLayout.style.js
  src/theme/theme.js
Labels: 🎨 Style

#86 [FEAT] Feature/#79 채팅 api 연결 및 ui 구현
  package.json
  src/App.jsx
  src/apis/auth.js
  src/apis/axios.js
  src/apis/chat.js
  src/apis/family.js
  src/apis/image.js
  src/apis/index.js
  src/apis/queryClient.js
  src/assets/images/chatRoomImg.webp
  src/components/chat/changeroom/ChangeRoom.jsx
  src/components/chat/changeroom/ChangeRoom.style.js
  src/components/chat/chatbar/Chatbar.jsx
  src/components/chat/chatbar/Chatbar.style.js
  src/components/chat/chatroom/ChatRoom.jsx
  src/components/chat/chatroom/ChatRoom.style.js
  src/components/chat/message/Message.jsx
  src/components/chat/message/Message.style.js
  src/components/chat/modal/Modal.jsx
  src/components/chat/modal/Modal.style.js
  src/components/common/checkbox/checkbox.jsx
  src/components/common/checkbox/checkbox.style.js
  src/components/common/dropdown/Dropdown.jsx
  src/components/common/dropdown/Dropdown.style.js
  src/components/common/popover/PopOver.jsx
  src/components/form/signupForm/SignupForm.jsx
  src/components/index.js
  src/constants/index.js
  src/constants/key.js
  src/constants/path.js
  src/container/ErrorBoundaryProvider.jsx
  src/hooks/queries/chat/useCreateChatRoom.js
  src/hooks/queries/chat/useExitChatRoom.js
  src/hooks/queries/chat/useGetChatRoom.js
  src/hooks/queries/chat/usePatchChatRoom.js
  src/hooks/queries/family/useGetFamilyList.js
  src/hooks/queries/image/useGetRealImage.js
  src/hooks/queries/login/useLogin.js
  src/layout/auth/AuthLayout.jsx
  src/main.jsx
  src/pages/chat/ChatMainPage.jsx
  src/pages/chat/ChatMainPage.style.js
  src/pages/main/MainPage.jsx
  src/store/index.js
  src/store/useAuthStore.js
  src/store/useChatRoom.js
  src/store/useDropdownStore.js
  src/store/useModalStore.js
  src/theme/theme.js
  src/utils/header.js
Labels: ✨ Feat

#88 [Feat] feature/#87 sidebar 반응형 짤리는거 수정
  src/layout/home/HomeLayout.style.js
Labels: 🎨 Style

#40 [Feat]feature/#39 가족 관리 페이지 구현 (미완)
  src/App.jsx
  src/assets/data/data.jsx
  src/components/common/alert/alert.jsx
  src/components/common/button/CustomButton.jsx
  src/components/common/button/CustomButton.style.js
  src/components/common/tooltip/Tooltip.style.js
  src/constants/path.js
  src/pages/index.js
  src/pages/setting/FamilySettings/FamilySettings.jsx
  src/pages/setting/FamilySettings/FamilySettings.style.js
  src/pages/setting/FamilySpaceSettings/FamilySpaceSettings.jsx
  src/pages/setting/FamilySpaceSettings/FamilySpaceSettings.style.js
Labels: ✨ Feat

#90 [Feat]feature/#83 photomainpage, alertpage 반응형 구현(완)
  src/components/common/calendar/CustomCalendar.style.js
  src/components/common/dropdown/Dropdown.style.js
  src/pages/alert/AlertMainPage.style.js
  src/pages/photo/PhotoMainPage.jsx
  src/pages/photo/PhotoMainPage.style.js
  src/pages/photo/components/PhotoPostModal.style.js
Labels: ✨ Feat

#93 [Style] feature/#92 회원가입 로그인 모바일 버전 디자인 변경 (완)
  src/components/form/loginForm/LoginForm.style.js
  src/pages/login/LoginPage.style.js
  src/pages/signup/SignupPage.style.js
Labels: 🎨 Style

#99 [Feat] feature/#94 회원가입 이미지 api 연결 (완)
  src/apis/chat.js
  src/apis/index.js
  src/components/chat/changeroom/ChangeRoom.jsx
  src/components/chat/chatbar/Chatbar.jsx
  src/components/chat/chatroom/ChatRoom.jsx
  src/components/common/input/CustomInput.style.js
  src/components/form/signupForm/SignupForm.jsx
  src/hooks/useFile.js
Labels: ✨ Feat

#60 [Feat]feature/#59 가족 목록 페이지 구현 (완)
  src/App.jsx
  src/assets/data/data.jsx
  src/assets/images/moresetting.png
  src/components/common/input/CustomInput.style.js
  src/pages/family/FamilyEdit/FamilyEdit.jsx
  src/pages/family/FamilyEdit/FamilyEdit.style.js
  src/pages/family/FamilyList/FamilyList.jsx
  src/pages/family/FamilyList/FamilyList.style.js
  src/pages/family/FamilyMainPage.jsx
  src/pages/family/FamilyMainPage.style.js
  src/pages/index.js
Labels: ✨ Feat

#111 [Bug] bug/#110 회원가입 이미지 변수명 수정(imageKeyName)
  src/App.jsx
  src/apis/auth.js
  src/components/form/signupForm/SignupForm.jsx
  src/pages/index.js
Labels: 🐞 bug

#106 [Style] feature/#104 회원가입 배경색 수정 & 레이아웃 100dvh 수정 (완)
  src/components/common/navbar/Navbar.style.js
  src/layout/auth/AuthLayout.style.js
  src/pages/login/LoginPage.style.js
  src/pages/signup/SignupPage.style.js
Labels: 🎨 Style

#97 [Feat] feature/#96 navbar sidebar 유저정보설정 - 사용자 정보조회 api 연결 (완)
  src/apis/index.js
  src/apis/user.js
  src/assets/images/profile.webp
  src/components/common/navbar/Navbar.jsx
  src/components/common/navbar/Navbar.style.js
  src/components/common/sidebar/SideBar.jsx
  src/constants/key.js
  src/constants/path.js
  src/hooks/queries/user/useGetProfile.js
  src/hooks/queries/user/useGetUserImg.js
Labels: ✨ Feat

#46 [Feat]feature/#45 로그아웃 페이지 구현 (완)
  package.json
  src/App.jsx
  src/components/common/alert/alert.jsx
  src/components/common/alert/alert.style.js
  src/constants/path.js
  src/pages/index.js
  src/pages/setting/Logout/Logout.jsx
  src/pages/setting/Logout/Logout.style.js
Labels: ✨ Feat

#44 [Feat]feature/#43 알림 설정 페이지 구현 (완)
  src/App.jsx
  src/components/common/checkbox/CheckBox.jsx
  src/components/common/checkbox/CheckBox.style.js
  src/pages/index.js
  src/pages/setting/FamilySpaceSettings/FamilySpaceSettings.style.js
  src/pages/setting/NotificationSettings/NotificationSettings.jsx
  src/pages/setting/NotificationSettings/NotificationSettings.style.js
Labels: ✨ Feat

#48 [Feat]feature/#47 탈퇴하기 페이지 구현 (완)
  src/App.jsx
  src/components/common/alert/alert.jsx
  src/constants/path.js
  src/pages/index.js
  src/pages/setting/DeleteAccount/DeleteAccount.jsx
Labels: ✨ Feat

#54 [Feat]feature/#49 비밀번호 변경 페이지 구현 (완)
  src/App.jsx
  src/components/common/input/CustomInput.jsx
  src/components/common/input/CustomInput.style.js
  src/constants/path.js
  src/pages/index.js
  src/pages/setting/ChangePassword/ChangePassword.jsx
  src/pages/setting/ChangePassword/ChangePassword.style.js
Labels: ✨ Feat

#114 [Feat] feature/#113 회원가입 이메일 인증 코드 api 연결 (완)
  src/apis/auth.js
  src/apis/image.js
  src/components/form/signupForm/SignupForm.jsx
  src/components/form/signupForm/SignupForm.style.js
  src/constants/path.js
  src/hooks/queries/signup/useCheckEmailCode.js
  src/hooks/queries/signup/useGetEmailCode.js
  src/hooks/useForm.js
  src/pages/login/LoginPage.style.js
Labels: ✨ Feat

#107 [Feat] feature/#105 채팅방에 속한 유저 api 연결 및 채팅 페이지로 분리 & 웹소켓 (미완)
  package.json
  src/App.jsx
  src/apis/chat.js
  src/apis/family.js
  src/components/chat/changeroom/ChangeRoom.jsx
  src/components/chat/changeroom/ChangeRoom.style.js
  src/components/chat/chatbar/Chatbar.jsx
  src/components/chat/chatbar/Chatbar.style.js
  src/components/chat/chatroom/ChatRoom.jsx
  src/components/chat/chatroom/ChatRoom.style.js
  src/components/chat/memberInfo/MemberInfo.jsx
  src/components/chat/memberInfo/MemberInfo.style.js
  src/components/chat/message/Message.jsx
  src/components/chat/message/Message.style.js
  src/components/chat/modal/Modal.jsx
  src/components/chat/receivemessage/ReceiveMessage.jsx
  src/components/chat/receivemessage/ReceiveMessage.style.js
  src/components/chat/webSocket/WebSocket.jsx
  src/components/common/alert/alert.jsx
  src/components/common/alert/alert.style.js
  src/components/common/avatar/Avatar.jsx
  src/components/common/avatar/Avatar.style.js
  src/components/common/button/CustomButton.jsx
  src/components/common/checkbox/CheckBox.jsx
  src/components/common/checkbox/checkbox.jsx
  src/components/common/sidebar/SideBar.jsx
  src/components/common/sidebar/SideBar.style.js
  src/components/index.js
  src/constants/image.js
  src/constants/index.js
  src/constants/path.js
  src/hooks/queries/chat/useGetChatRoom.js
  src/hooks/queries/chat/useGetChatRoomUsers.js
  src/hooks/queries/chat/useGetMemberProfile.js
  src/hooks/queries/chat/useGetMessage.js
  src/hooks/queries/family/useGetFamilyImg.js
  src/hooks/queries/family/useGetFamilySpaceId.js
  src/hooks/useThrottling.js
  src/layout/home/HomeLayout.jsx
  src/layout/home/HomeLayout.style.js
  src/pages/chat/ChatMainPage.jsx
  src/pages/chat/ChatMainPage.style.js
  src/pages/chat/chat-detail/ChatDetailPage.jsx
  src/pages/chat/chat-detail/ChatDetailPage.style.js
  src/pages/chat/chat-modifiy/ChatImgPage.jsx
  src/pages/chat/chat-user-info/ChatUserInfo.jsx
  src/pages/chat/chat-user-info/ChatUserInfo.style.js
  src/pages/index.js
  src/store/useUserIdStore.js
  src/store/useWebSocketStore.js
Labels: ✨ Feat

#120 [Feat] feature/#117 서비스 이용 페이지 관련 api 연결
  package.json
  src/apis/family.js
  src/constants/path.js
  src/hooks/queries/family/useCheckSpaceCode.js
  src/hooks/queries/family/useCreateFamilyspace.js
  src/hooks/queries/family/useEnterSpace.js
  src/main.jsx
  src/pages/service/CreateSpace/CreateSpace.jsx
  src/pages/service/CreateSpace/CreateSpace.style.js
  src/pages/service/InvitationLink/InvitationLink.jsx
  src/pages/service/InvitationLink/InvitationLink.style.js
  src/pages/service/ServiceMainPage/ServiceMainPage.jsx
  src/store/useFamilySpaceStore.js
  src/utils/index.js
  src/utils/validate.js
Labels: ✨ Feat

#58 [FEAT]feature/#57 게시글 작성 페이지(미완)
  .eslintrc.cjs
  src/apis/index.js
  src/apis/post.js
  src/components/Comment/Comment.jsx
  src/components/Comment/Comment.style.js
  src/components/common/modal/PostModal.jsx
  src/components/common/modal/PostModal.style.js
  src/components/common/popover/PopOver.jsx
  src/components/common/popover/PopOver.style.js
  src/components/common/sidebar/SideBar.jsx
  src/constants/boardList.js
  src/constants/path.js
  src/hooks/queries/posts/useGetPosts.js
  src/hooks/useFamilySpaceId.js
  src/hooks/usePost.js
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.style.js
Labels: ✨ Feat

#102 [FEAT] feature/#91 일정 페이지 구현
  .eslintrc.cjs
  src/App.jsx
  src/constants/path.js
  src/pages/calender/AddSchedule.jsx
  src/pages/calender/AddSchedule.style.js
  src/pages/calender/CalenderMainPage.jsx
  src/pages/calender/CalenderMainPage.style.js
  src/pages/index.js
Labels: ✨ Feat

#108 [ Style]feature/#89 SettingBar 반응현 구현 (미완)
  src/assets/images/moreBox.png
  src/components/Settingbar/Settingbar.jsx
  src/components/Settingbar/Settingbar.style.js
  src/components/common/sidebar/SideBar.jsx
  src/components/common/sidebar/SideBar.style.js
  src/pages/service/ServiceMainPage/ServiceMainPage.style.js
Labels: 🎨 Style

#112 [Feat]feature/#109 가족 차단 및 차단해제 api 연결 (미완)
  package.json
  src/apis/family.js
  src/apis/index.js
  src/apis/posts.js
  src/apis/user.js
  src/components/common/alert/alert.style.js
  src/components/index.js
  src/components/setting/familyMember/FamilyMember.jsx
  src/components/setting/familyMember/FamilyMember.style.js
  src/components/setting/userBox/UserBox.jsx
  src/components/setting/userBox/UserBox.style.js
  src/constants/key.js
  src/constants/path.js
  src/hooks/queries/family/useBlockFamilyMember.js
  src/hooks/queries/family/useUnblockFamilyMember.js
  src/hooks/queries/family/useUpdateFamilyMember.js
  src/hooks/queries/posts/useGetMyPosts.js
  src/pages/family/FamilyEdit/FamilyEdit.jsx
  src/pages/family/FamilyList/FamilyList.jsx
  src/pages/family/FamilyList/FamilyList.style.js
  src/pages/setting/FamilySettings/FamilySettings.jsx
  src/pages/setting/FamilySettings/FamilySettings.style.js
  src/pages/setting/MyPosts/MyPosts.jsx
  src/pages/setting/MyPosts/MyPosts.style.js
Labels: ✨ Feat

#121 [Feat]feature/#118 알림 설정 페이지 api 연결
  src/apis/notifications.js
  src/constants/key.js
  src/constants/path.js
  src/hooks/queries/notifications/useNotificationSettings.js
  src/pages/setting/NotificationSettings/NotificationSettings.jsx
Labels: ✨ Feat

#132 [Bug] bug/#131 로그아웃 후 캐시된 데이터 삭제 #131
  src/hooks/queries/user/useDeleteAccount.js
  src/hooks/queries/user/useLogout.js
Labels: 🐞 bug

#126 [Feat] feature/#125 서비스 이용페이지 api 수정 & ui 수정 (완)
  src/assets/images/CreateSpace.png
  src/assets/images/InvitationLink.png
  src/components/chat/webSocket/WebSocket.jsx
  src/hooks/queries/family/useCheckSpaceCode.js
  src/pages/service/InvitationLink/InvitationLink.jsx
  src/pages/service/ServiceMainPage/ServiceMainPage.jsx
  src/pages/service/ServiceMainPage/ServiceMainPage.style.js
Labels: ✨ Feat

#130 [Feat] feature/#127 가족티콘 api 연결 & UI 구현 (완)
  src/apis/chat.js
  src/assets/images/landing.webp
  src/components/chat/emoticon/Emoticon.jsx
  src/components/chat/emoticon/Emoticon.style.js
  src/components/chat/message/Message.jsx
  src/components/chat/message/Message.style.js
  src/components/chat/modal/filemodal/FileModal.jsx
  src/components/chat/modal/filemodal/FileModal.sytle.js
  src/components/index.js
  src/constants/key.js
  src/constants/path.js
  src/hooks/queries/chat/useDeleteEmoticon.js
  src/hooks/queries/chat/useGetEmoticon.js
  src/hooks/queries/chat/useGetMessage.js
  src/hooks/queries/chat/usePostEmoticon.js
  src/hooks/queries/family/useGetFamilySpaceID.js
  src/hooks/queries/family/useGetFamilySpaceId.js
  src/hooks/queries/image/useGetEmoticonImg.js
  src/hooks/useFamilySpaceId.js
  src/hooks/useFile.js
  src/pages/landing/LadingPage.jsx
  src/pages/landing/LandingPage.style.js
  src/store/useModalStore.js
Labels: ✨ Feat

#140 [Feat] feature/#139 랜딩페이지 ui & navbar q&n 삭제
  package.json
  src/assets/images/landing2.webp
  src/components/animation/Animation.jsx
  src/components/common/navbar/Navbar.jsx
  src/components/common/navbar/Navbar.style.js
  src/pages/landing/LadingPage.jsx
  src/pages/landing/LandingPage.style.js
Labels: ✨ Feat

#134 [Feat]feature/#129 알림 설정 페이지 api 연결
  src/apis/notifications.js
  src/apis/post.js
  src/constants/path.js
  src/hooks/queries/notifications/useNotificationSettings.js
  src/hooks/queries/posts/useGetMyPosts.js
  src/pages/setting/MyPosts/MyPosts.jsx
  src/pages/setting/NotificationSettings/NotificationSettings.jsx
Labels: ✨ Feat

#142 [Feat]feature/#135 가족 공간 삭제 및 코드 재발급 api 연결
  src/apis/family.js
  src/hooks/queries/family/useDeleteFamilySpace.js
  src/pages/setting/FamilySpaceSettings/FamilySpaceSettings.jsx
  src/pages/setting/FamilySpaceSettings/FamilySpaceSettings.style.js
  src/theme/theme.js
Labels: ✨ Feat

#141 [Feat] feature/#137 채팅 가족티콘 보내기 수정 & 무한스크롤 (완)
  src/apis/image.js
  src/components/chat/changeroom/ChangeRoom.jsx
  src/components/chat/chatbar/Chatbar.jsx
  src/components/chat/chatbar/Chatbar.style.js
  src/components/chat/chatroom/ChatRoom.jsx
  src/components/chat/emoticon/Emoticon.jsx
  src/components/chat/emoticon/Emoticon.style.js
  src/components/chat/message/Message.jsx
  src/components/chat/message/Message.style.js
  src/components/chat/message/myMessage/Mymessage.jsx
  src/components/chat/message/myMessage/Mymessage.style.js
  src/components/chat/modal/Modal.jsx
  src/components/chat/modal/filemodal/FileModal.jsx
  src/components/chat/receivemessage/ReceiveMessage.jsx
  src/components/chat/receivemessage/ReceiveMessage.style.js
  src/components/chat/webSocket/WebSocket.jsx
  src/hooks/queries/chat/useGetChatRoom.js
  src/hooks/queries/chat/useGetMessage.js
  src/hooks/queries/image/useGetSendEmoticon.js
  src/hooks/useFile.js
  src/store/useWebSocketStore.js
Labels: ✨ Feat

#145 [Bug] 역무한스크롤 버그 #144
  src/components/chat/message/Message.jsx
Labels: 🐞 bug

#133 [Feat] feature/#128 알림 페이지 api 연결
  src/apis/alert.js
  src/apis/index.js
  src/components/alertbox/AlertBox.jsx
  src/constants/key.js
  src/constants/path.js
  src/hooks/queries/alert/useGetAlert.js
  src/hooks/queries/alert/useGetProfileImg.js
  src/pages/alert/AlertMainPage.jsx
Labels: ✨ Feat

#146 [Feat]feature/#143 개인정보 수정 페이지, 비밀번호 변경 페이지 api 연결 (미완)
  src/apis/image.js
  src/apis/user.js
  src/constants/path.js
  src/hooks/queries/user/useChangePassword.js
  src/hooks/queries/user/useUpdateProfile.js
  src/pages/setting/ChangePassword/ChangePassword.jsx
  src/pages/setting/EditProfile/EditProfile.jsx
Labels: ✨ Feat

#150 [Feat] feature/#149 navbar 로그아웃 & 가족공간
  src/components/common/navbar/Navbar.jsx
  src/components/common/navbar/Navbar.style.js
  src/hooks/queries/family/useEnterFamily.js
Labels: ✨ Feat

#156 [Feat] feature/#153 일정 달력에 아이콘 반영
  src/apis/schedule.js
  src/components/common/calendar/CustomCalendar.jsx
  src/components/common/calendar/CustomCalendar.style.js
  src/components/dtype/Dtype.jsx
  src/components/dtype/Dtype.style.js
  src/constants/path.js
  src/hooks/queries/schedule/useGetDailySchedule.js
  src/hooks/queries/schedule/useGetMonthlySchedule.js
  src/mocks/event.js
  src/pages/calender/CalenderMainPage.jsx
  src/pages/calender/CalenderMainPage.style.js
  src/store/useCalendarStore.js
Labels: ✨ Feat

#158 [Feat] Feature/#151 채팅 수정
  src/components/chat/message/Message.jsx
  src/components/chat/webSocket/WebSocket.jsx
Labels: ✨ Feat

#160 [Feat]feature/#159 반응형 수정 및 비밀번호 변경 수정
  src/components/settingbar/Settingbar.jsx
  src/pages/setting/EditProfile/EditProfile.jsx
Labels: ✨ Feat

#167 [Style] feature/#164 일정 페이지 추가&수정 ui 고치기
  src/apis/axios.js
  src/pages/calender/AddSchedule.jsx
  src/pages/calender/AddSchedule.style.js
  src/pages/calender/PatchSchedule.jsx
  src/pages/calender/PatchSchedule.style.js
Labels: 🎨 Style

#169 [Feat]feature/#163 세팅바 반응형 수정
  src/apis/auth.js
  src/components/common/alert/alert.jsx
  src/components/common/alert/alert.style.js
  src/components/common/sidebar/SideBar.jsx
  src/components/common/sidebar/SideBar.style.js
  src/components/settingbar/Settingbar.jsx
  src/components/settingbar/Settingbar.style.js
  src/pages/setting/EditProfile/EditProfile.style.js
Labels: ✨ Feat

#155 [Feat]feature/#152 앨범 페이지 이미지 수정(완)
  src/apis/album.js
  src/hooks/queries/album/useGetRealAlbum.js
  src/pages/photo/PhotoMainPage.jsx
  src/pages/photo/components/PhotoPostModal.jsx
Labels: ✨ Feat

#173 [Style] feature/#172 랜딩페이지 완성
  src/components/index.js
  src/components/service/ServiceComponent.jsx
  src/pages/landing/LadingPage.jsx
  src/pages/landing/LandingPage.style.js
  src/pages/service/ServiceMainPage/ServiceMainPage.jsx
  src/pages/signup/SignupPage.jsx
Labels: 🎨 Style

#177 [Bug] bug/#176 캘린더 버그 수정
  src/components/common/calendar/CustomCalendar.jsx
  src/pages/photo/PhotoMainPage.jsx
  src/pages/photo/components/PhotoPostModal.style.js
  src/utils/formatData.js
Labels: 🐞 bug

#179 [Feat] feature/#178 sidebar 경로 수정 및 ui 수정
  src/components/alertbox/AlertBox.style.js
  src/components/common/sidebar/SideBar.jsx
  src/pages/alert/AlertMainPage.jsx
  src/pages/alert/AlertMainPage.style.js
  src/pages/calender/AddSchedule.jsx
  src/pages/calender/AddSchedule.style.js
  src/pages/calender/CalenderMainPage.jsx
  src/pages/calender/CalenderMainPage.style.js
Labels: ✨ Feat

#180 [Feat] Feature/#166 피드 홈 스타일 수정
  src/components/common/input/CustomInput.style.js
  src/components/common/newPopover/NewPopover.jsx
  src/components/common/newPopover/NewPopover.style.js
  src/components/home/PostItem.jsx
  src/components/home/PostItem.style.js
  src/components/post/Comment.jsx
  src/components/post/Comment.style.js
  src/components/post/patchmodal/PatchModal.jsx
  src/components/post/patchmodal/PatchModal.style.js
  src/pages/home/HomeMainPage.style.js
Labels: ✨ Feat

#162 [FEAT]feature/#161 게시글 페이지 스타일 수정
  src/components/common/modal/PostModal.jsx
  src/components/home/PostItem.style.js
  src/components/post/patchmodal/PatchModal.style.js
  src/pages/home/HomeMainPage.style.js
  src/pages/main/PostDetailPage.style.js
Labels: ✨ Feat

#182 [Feat] feature/#168 채팅 웹소켓 재연결 & 역무한스크롤
  src/components/chat/chatroom/ChatRoom.jsx
  src/components/chat/message/Message.jsx
  src/components/chat/webSocket/WebSocket.jsx
  src/hooks/queries/image/useGetRealImage.js
Labels: ✨ Feat

#184 [Feat] feature/#183 home 페이지 수정
  src/components/chat/message/Message.jsx
  src/components/home/PostItem.jsx
  src/components/home/PostItem.style.js
  src/components/post/Comment.style.js
  src/pages/main/PostDetailPage.style.js
Labels: ✨ Feat

#187 [Feat]feature/#181 더보기 모바일 화면 수정
  src/assets/images/plusSetting.png
  src/components/setting/familyMember/FamilyMember.jsx
  src/components/setting/familyMember/FamilyMember.style.js
  src/pages/family/FamilyList/FamilyList.jsx
  src/pages/family/FamilyList/FamilyList.style.js
Labels: ✨ Feat

#188 [Feat] feature/#185 게시글 생성 모달 수정
  src/components/common/modal/PostModal.jsx
  src/components/home/PostItem.style.js
  src/components/service/ServiceComponent.jsx
  src/hooks/queries/posts/useDeletePost.js
Labels: 🎨 Style

#189 develop to main
  src/assets/images/plusSetting.png
  src/components/common/modal/PostModal.jsx
  src/components/home/PostItem.style.js
  src/components/service/ServiceComponent.jsx
  src/components/setting/familyMember/FamilyMember.jsx
  src/components/setting/familyMember/FamilyMember.style.js
  src/hooks/queries/posts/useDeletePost.js
  src/pages/family/FamilyList/FamilyList.jsx
  src/pages/family/FamilyList/FamilyList.style.js
Labels: 🌏 Deploy
